version: "3"
services:
  server:
    volumes:
      - ../config.ini:/app/config.ini
      - ../gRPC:/app/client/gRPC
    build: .
    network_mode: host
    ports:
      - "9876:9876"
    command: sh init.sh