version: "3"
services:
  server:
    build: .
    volumes:
      - ./config.ini:/app/config.ini
    ports:
      - "3333:3333"
      - "9876:9876"
    extra_hosts:
      - "host.docker.internal:host-gateway"
